title: Angebote
fields:
  -
    handle: service
    field:
      type: replicator
      display: Angebot
      sets:
        neue_set-gruppe:
          display: 'Neue Set-Gruppe'
          sets:
            card:
              display: Kachel
              instructions: 'Angebot hinzufügen'
              icon: media-image-picture-orientation
              fields:
                -
                  handle: title
                  field:
                    type: text
                    display: Titel
                    validate:
                      - required
                -
                  handle: illustration
                  field:
                    max_files: 1
                    container: assets
                    type: assets
                    display: Illustration
                    validate:
                      - required
                    folder: illustrationen
                -
                  handle: link
                  field:
                    collections:
                      - pages
                    type: link
                    display: Link
