title: Settings
fields:
  -
    handle: page_theme
    field:
      options:
        general: Allgemein
        laundry: Wäscherei
        nursery: Chinderhuus
      default: general
      type: select
      display: Bereich
  -
    handle: page_class
    field:
      options:
        page-privacy: Datenschutz
        page-imprint: Impressum
      type: select
      display: 'Seiten CSS-Klasse'
  -
    handle: debug
    field:
      type: toggle
      display: Debug
  -
    handle: template
    field:
      type: template
      display: Template
  -
    handle: layout
    field:
      type: template
      display: Layout
