title: Settings
fields:
  -
    handle: shortcut_menu
    field:
      default: true
      type: toggle
      display: 'Shortcut "Menü"'
      width: 50
  -
    handle: shortcut_jobs
    field:
      default: true
      type: toggle
      display: 'Shortcut "Jobs"'
      width: 50
  -
    handle: page_theme
    field:
      options:
        general: Allgemein
        laundry: Wäscherei
        nursery: Chinderhuus
      default: general
      type: select
      display: Bereich
      width: 50
  -
    handle: page_class
    field:
      options:
        page-privacy: Datenschutz
        page-imprint: Impressum
      type: select
      display: 'Seiten CSS-Klasse'
      width: 50
  -
    handle: debug
    field:
      type: toggle
      display: Debug
  -
    handle: template
    field:
      type: template
      display: Template
  -
    handle: layout
    field:
      type: template
      display: Layout
